# Generated by Django 4.2.4 on 2023-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codecompanionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codecompaniontest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
