# Generated by Django 4.2.4 on 2023-09-20 10:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codecompanionapp', '0002_alter_codecompanionuser_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCompanionHRM',
            fields=[
                ('codecompanionuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hrmlevel', models.CharField(choices=[(1, 'Junior'), (2, 'Senior')], max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('codecompanionapp.codecompanionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodeCompanionSD',
            fields=[
                ('codecompanionuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sdlevel', models.CharField(choices=[(1, 'Junior'), (2, 'Senior')], max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('codecompanionapp.codecompanionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CodeCompanionSDM',
            fields=[
                ('codecompanionuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('sdmlevel', models.CharField(choices=[(1, 'Junior'), (2, 'Senior')], max_length=50)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('codecompanionapp.codecompanionuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='codecompanionuser',
            name='role',
        ),
        migrations.AddField(
            model_name='codecompanionuser',
            name='ROLE',
            field=models.CharField(choices=[('SOFTWAREDEVELOPER', 'Software Developer'), ('SOFTWAREDEVELOPMENTMANAGER', 'Software Development Manager'), ('HUMANRESOURCEMANAGER', 'Human Resource Manager')], default='SOFTWAREDEVELOPER', max_length=50),
        ),
    ]
